((%contiguous->py-buffer (cyclone python) python)
 (%initialized? (cyclone python) python)
 (%long->py-bool (cyclone python) python)
 (%long->py-long (cyclone python) python)
 (%make-iset (cyclone iset) iset)
 (%py-apply (cyclone python) python)
 (%py-bool->bool (cyclone python) python)
 (%py-buffer->contiguous (cyclone python) python)
 (%py-buffer-release (cyclone python) python)
 (%py-buffer-size (cyclone python) python)
 (%py-callable-check (cyclone python) python)
 (%py-decref (cyclone python) python)
 (%py-dict-get-item (cyclone python) python)
 (%py-dict-get-item-string
   (cyclone python)
   python)
 (%py-dict-items (cyclone python) python)
 (%py-dict-keys (cyclone python) python)
 (%py-dict-new (cyclone python) python)
 (%py-dict-set-item (cyclone python) python)
 (%py-dict-size (cyclone python) python)
 (%py-err-as-string (cyclone python) python)
 (%py-err-clear (cyclone python) python)
 (%py-err-occurred (cyclone python) python)
 (%py-error (cyclone python) python)
 (%py-eval (cyclone python) python)
 (%py-finalize (cyclone python) python)
 (%py-float->double (cyclone python) python)
 (%py-float-from-double (cyclone python) python)
 (%py-import (cyclone python) python)
 (%py-import-add-module (cyclone python) python)
 (%py-import-get-module-dict
   (cyclone python)
   python)
 (%py-import-module (cyclone python) python)
 (%py-import-module-ex (cyclone python) python)
 (%py-incref (cyclone python) python)
 (%py-initialize (cyclone python) python)
 (%py-is-initialized (cyclone python) python)
 (%py-list-get-item (cyclone python) python)
 (%py-list-new (cyclone python) python)
 (%py-list-set-item (cyclone python) python)
 (%py-list-size (cyclone python) python)
 (%py-long->long (cyclone python) python)
 (%py-module-add-object (cyclone python) python)
 (%py-module-get-dict (cyclone python) python)
 (%py-module-get-dict-as-ptr
   (cyclone python)
   python)
 (%py-object-call (cyclone python) python)
 (%py-object-call-object (cyclone python) python)
 (%py-object-get-attr-string
   (cyclone python)
   python)
 (%py-object-get-buffer (cyclone python) python)
 (%py-object-set-attr-string
   (cyclone python)
   python)
 (%py-object-str (cyclone python) python)
 (%py-object-type (cyclone python) python)
 (%py-run-file (cyclone python) python)
 (%py-run-simple-string (cyclone python) python)
 (%py-run-string (cyclone python) python)
 (%py-str->string (cyclone python) python)
 (%py-str->string-and-size
   (cyclone python)
   python)
 (%py-tuple-get-item (cyclone python) python)
 (%py-tuple-new (cyclone python) python)
 (%py-tuple-set-item (cyclone python) python)
 (%py-tuple-size (cyclone python) python)
 (%python->scm (cyclone python) python)
 (%python-exception-string
   (cyclone python)
   python)
 (%raise-python-exception (cyclone python) python)
 (%scm->python (cyclone python) python)
 (%string->py-str (cyclone python) python)
 (%with-initialization-check
   (cyclone python)
   python)
 (*py-functions* (cyclone python) python)
 (-> (cyclone clojurian) clojurian)
 (->* (cyclone clojurian) clojurian)
 (->> (cyclone clojurian) clojurian)
 (->>* (cyclone clojurian) clojurian)
 (->string (cyclone python) python)
 (ALERT (cyclone syslog) syslog)
 (CRIT (cyclone syslog) syslog)
 (CURLOPT_ACCEPTTIMEOUT_MS (cyclone curl) curl)
 (CURLOPT_ACCEPT_ENCODING (cyclone curl) curl)
 (CURLOPT_ADDRESS_SCOPE (cyclone curl) curl)
 (CURLOPT_APPEND (cyclone curl) curl)
 (CURLOPT_AUTOREFERER (cyclone curl) curl)
 (CURLOPT_BUFFERSIZE (cyclone curl) curl)
 (CURLOPT_CAINFO (cyclone curl) curl)
 (CURLOPT_CAPATH (cyclone curl) curl)
 (CURLOPT_CERTINFO (cyclone curl) curl)
 (CURLOPT_CHUNK_BGN_FUNCTION (cyclone curl) curl)
 (CURLOPT_CHUNK_DATA (cyclone curl) curl)
 (CURLOPT_CHUNK_END_FUNCTION (cyclone curl) curl)
 (CURLOPT_CLOSESOCKETDATA (cyclone curl) curl)
 (CURLOPT_CLOSESOCKETFUNCTION (cyclone curl) curl)
 (CURLOPT_CONNECTTIMEOUT (cyclone curl) curl)
 (CURLOPT_CONNECTTIMEOUT_MS (cyclone curl) curl)
 (CURLOPT_CONNECT_ONLY (cyclone curl) curl)
 (CURLOPT_CONV_FROM_NETWORK_FUNCTION
   (cyclone curl)
   curl)
 (CURLOPT_CONV_FROM_UTF8_FUNCTION
   (cyclone curl)
   curl)
 (CURLOPT_CONV_TO_NETWORK_FUNCTION
   (cyclone curl)
   curl)
 (CURLOPT_COOKIE (cyclone curl) curl)
 (CURLOPT_COOKIEFILE (cyclone curl) curl)
 (CURLOPT_COOKIEJAR (cyclone curl) curl)
 (CURLOPT_COOKIELIST (cyclone curl) curl)
 (CURLOPT_COOKIESESSION (cyclone curl) curl)
 (CURLOPT_COPYPOSTFIELDS (cyclone curl) curl)
 (CURLOPT_CRLF (cyclone curl) curl)
 (CURLOPT_CRLFILE (cyclone curl) curl)
 (CURLOPT_CUSTOMREQUEST (cyclone curl) curl)
 (CURLOPT_DEBUGDATA (cyclone curl) curl)
 (CURLOPT_DEBUGFUNCTION (cyclone curl) curl)
 (CURLOPT_DEFAULT_PROTOCOL (cyclone curl) curl)
 (CURLOPT_DIRLISTONLY (cyclone curl) curl)
 (CURLOPT_DNS_CACHE_TIMEOUT (cyclone curl) curl)
 (CURLOPT_DNS_INTERFACE (cyclone curl) curl)
 (CURLOPT_DNS_LOCAL_IP4 (cyclone curl) curl)
 (CURLOPT_DNS_LOCAL_IP6 (cyclone curl) curl)
 (CURLOPT_DNS_SERVERS (cyclone curl) curl)
 (CURLOPT_DNS_USE_GLOBAL_CACHE
   (cyclone curl)
   curl)
 (CURLOPT_EGDSOCKET (cyclone curl) curl)
 (CURLOPT_ERRORBUFFER (cyclone curl) curl)
 (CURLOPT_EXPECT_100_TIMEOUT_MS
   (cyclone curl)
   curl)
 (CURLOPT_FAILONERROR (cyclone curl) curl)
 (CURLOPT_FILETIME (cyclone curl) curl)
 (CURLOPT_FNMATCH_DATA (cyclone curl) curl)
 (CURLOPT_FNMATCH_FUNCTION (cyclone curl) curl)
 (CURLOPT_FOLLOWLOCATION (cyclone curl) curl)
 (CURLOPT_FORBID_REUSE (cyclone curl) curl)
 (CURLOPT_FRESH_CONNECT (cyclone curl) curl)
 (CURLOPT_FTPPORT (cyclone curl) curl)
 (CURLOPT_FTPSSLAUTH (cyclone curl) curl)
 (CURLOPT_FTP_ACCOUNT (cyclone curl) curl)
 (CURLOPT_FTP_ALTERNATIVE_TO_USER
   (cyclone curl)
   curl)
 (CURLOPT_FTP_CREATE_MISSING_DIRS
   (cyclone curl)
   curl)
 (CURLOPT_FTP_FILEMETHOD (cyclone curl) curl)
 (CURLOPT_FTP_RESPONSE_TIMEOUT
   (cyclone curl)
   curl)
 (CURLOPT_FTP_SKIP_PASV_IP (cyclone curl) curl)
 (CURLOPT_FTP_SSL_CCC (cyclone curl) curl)
 (CURLOPT_FTP_USE_EPRT (cyclone curl) curl)
 (CURLOPT_FTP_USE_EPSV (cyclone curl) curl)
 (CURLOPT_FTP_USE_PRET (cyclone curl) curl)
 (CURLOPT_GSSAPI_DELEGATION (cyclone curl) curl)
 (CURLOPT_HEADER (cyclone curl) curl)
 (CURLOPT_HEADERDATA (cyclone curl) curl)
 (CURLOPT_HEADERFUNCTION (cyclone curl) curl)
 (CURLOPT_HEADEROPT (cyclone curl) curl)
 (CURLOPT_HTTP200ALIASES (cyclone curl) curl)
 (CURLOPT_HTTPAUTH (cyclone curl) curl)
 (CURLOPT_HTTPGET (cyclone curl) curl)
 (CURLOPT_HTTPHEADER (cyclone curl) curl)
 (CURLOPT_HTTPPOST (cyclone curl) curl)
 (CURLOPT_HTTPPROXYTUNNEL (cyclone curl) curl)
 (CURLOPT_HTTP_CONTENT_DECODING
   (cyclone curl)
   curl)
 (CURLOPT_HTTP_TRANSFER_DECODING
   (cyclone curl)
   curl)
 (CURLOPT_HTTP_VERSION (cyclone curl) curl)
 (CURLOPT_IGNORE_CONTENT_LENGTH
   (cyclone curl)
   curl)
 (CURLOPT_INFILESIZE (cyclone curl) curl)
 (CURLOPT_INFILESIZE_LARGE (cyclone curl) curl)
 (CURLOPT_INTERFACE (cyclone curl) curl)
 (CURLOPT_INTERLEAVEDATA (cyclone curl) curl)
 (CURLOPT_INTERLEAVEFUNCTION (cyclone curl) curl)
 (CURLOPT_IOCTLDATA (cyclone curl) curl)
 (CURLOPT_IOCTLFUNCTION (cyclone curl) curl)
 (CURLOPT_IPRESOLVE (cyclone curl) curl)
 (CURLOPT_ISSUERCERT (cyclone curl) curl)
 (CURLOPT_KEYPASSWD (cyclone curl) curl)
 (CURLOPT_KRBLEVEL (cyclone curl) curl)
 (CURLOPT_LOCALPORT (cyclone curl) curl)
 (CURLOPT_LOCALPORTRANGE (cyclone curl) curl)
 (CURLOPT_LOGIN_OPTIONS (cyclone curl) curl)
 (CURLOPT_LOW_SPEED_LIMIT (cyclone curl) curl)
 (CURLOPT_LOW_SPEED_TIME (cyclone curl) curl)
 (CURLOPT_MAIL_AUTH (cyclone curl) curl)
 (CURLOPT_MAIL_FROM (cyclone curl) curl)
 (CURLOPT_MAIL_RCPT (cyclone curl) curl)
 (CURLOPT_MAXCONNECTS (cyclone curl) curl)
 (CURLOPT_MAXFILESIZE (cyclone curl) curl)
 (CURLOPT_MAXFILESIZE_LARGE (cyclone curl) curl)
 (CURLOPT_MAXREDIRS (cyclone curl) curl)
 (CURLOPT_MAX_RECV_SPEED_LARGE
   (cyclone curl)
   curl)
 (CURLOPT_MAX_SEND_SPEED_LARGE
   (cyclone curl)
   curl)
 (CURLOPT_NETRC (cyclone curl) curl)
 (CURLOPT_NETRC_FILE (cyclone curl) curl)
 (CURLOPT_NEW_DIRECTORY_PERMS (cyclone curl) curl)
 (CURLOPT_NEW_FILE_PERMS (cyclone curl) curl)
 (CURLOPT_NOBODY (cyclone curl) curl)
 (CURLOPT_NOPROGRESS (cyclone curl) curl)
 (CURLOPT_NOPROXY (cyclone curl) curl)
 (CURLOPT_NOSIGNAL (cyclone curl) curl)
 (CURLOPT_OPENSOCKETDATA (cyclone curl) curl)
 (CURLOPT_OPENSOCKETFUNCTION (cyclone curl) curl)
 (CURLOPT_PASSWORD (cyclone curl) curl)
 (CURLOPT_PATH_AS_IS (cyclone curl) curl)
 (CURLOPT_PINNEDPUBLICKEY (cyclone curl) curl)
 (CURLOPT_PIPEWAIT (cyclone curl) curl)
 (CURLOPT_PORT (cyclone curl) curl)
 (CURLOPT_POST (cyclone curl) curl)
 (CURLOPT_POSTFIELDS (cyclone curl) curl)
 (CURLOPT_POSTFIELDSIZE (cyclone curl) curl)
 (CURLOPT_POSTFIELDSIZE_LARGE (cyclone curl) curl)
 (CURLOPT_POSTQUOTE (cyclone curl) curl)
 (CURLOPT_POSTREDIR (cyclone curl) curl)
 (CURLOPT_PREQUOTE (cyclone curl) curl)
 (CURLOPT_PRIVATE (cyclone curl) curl)
 (CURLOPT_PROGRESSDATA (cyclone curl) curl)
 (CURLOPT_PROGRESSFUNCTION (cyclone curl) curl)
 (CURLOPT_PROTOCOLS (cyclone curl) curl)
 (CURLOPT_PROXY (cyclone curl) curl)
 (CURLOPT_PROXYAUTH (cyclone curl) curl)
 (CURLOPT_PROXYHEADER (cyclone curl) curl)
 (CURLOPT_PROXYPASSWORD (cyclone curl) curl)
 (CURLOPT_PROXYPORT (cyclone curl) curl)
 (CURLOPT_PROXYTYPE (cyclone curl) curl)
 (CURLOPT_PROXYUSERNAME (cyclone curl) curl)
 (CURLOPT_PROXYUSERPWD (cyclone curl) curl)
 (CURLOPT_PROXY_SERVICE_NAME (cyclone curl) curl)
 (CURLOPT_PROXY_TRANSFER_MODE (cyclone curl) curl)
 (CURLOPT_PUT (cyclone curl) curl)
 (CURLOPT_QUOTE (cyclone curl) curl)
 (CURLOPT_RANDOM_FILE (cyclone curl) curl)
 (CURLOPT_RANGE (cyclone curl) curl)
 (CURLOPT_READDATA (cyclone curl) curl)
 (CURLOPT_READFUNCTION (cyclone curl) curl)
 (CURLOPT_REDIR_PROTOCOLS (cyclone curl) curl)
 (CURLOPT_REFERER (cyclone curl) curl)
 (CURLOPT_RESOLVE (cyclone curl) curl)
 (CURLOPT_RESUME_FROM (cyclone curl) curl)
 (CURLOPT_RESUME_FROM_LARGE (cyclone curl) curl)
 (CURLOPT_RTSP_CLIENT_CSEQ (cyclone curl) curl)
 (CURLOPT_RTSP_REQUEST (cyclone curl) curl)
 (CURLOPT_RTSP_SERVER_CSEQ (cyclone curl) curl)
 (CURLOPT_RTSP_SESSION_ID (cyclone curl) curl)
 (CURLOPT_RTSP_STREAM_URI (cyclone curl) curl)
 (CURLOPT_RTSP_TRANSPORT (cyclone curl) curl)
 (CURLOPT_SASL_IR (cyclone curl) curl)
 (CURLOPT_SEEKDATA (cyclone curl) curl)
 (CURLOPT_SEEKFUNCTION (cyclone curl) curl)
 (CURLOPT_SERVICE_NAME (cyclone curl) curl)
 (CURLOPT_SHARE (cyclone curl) curl)
 (CURLOPT_SOCKOPTDATA (cyclone curl) curl)
 (CURLOPT_SOCKOPTFUNCTION (cyclone curl) curl)
 (CURLOPT_SOCKS5_GSSAPI_NEC (cyclone curl) curl)
 (CURLOPT_SOCKS5_GSSAPI_SERVICE
   (cyclone curl)
   curl)
 (CURLOPT_SSH_AUTH_TYPES (cyclone curl) curl)
 (CURLOPT_SSH_HOST_PUBLIC_KEY_MD5
   (cyclone curl)
   curl)
 (CURLOPT_SSH_KEYDATA (cyclone curl) curl)
 (CURLOPT_SSH_KEYFUNCTION (cyclone curl) curl)
 (CURLOPT_SSH_KNOWNHOSTS (cyclone curl) curl)
 (CURLOPT_SSH_PRIVATE_KEYFILE (cyclone curl) curl)
 (CURLOPT_SSH_PUBLIC_KEYFILE (cyclone curl) curl)
 (CURLOPT_SSLCERT (cyclone curl) curl)
 (CURLOPT_SSLCERTTYPE (cyclone curl) curl)
 (CURLOPT_SSLENGINE (cyclone curl) curl)
 (CURLOPT_SSLENGINE_DEFAULT (cyclone curl) curl)
 (CURLOPT_SSLKEY (cyclone curl) curl)
 (CURLOPT_SSLKEYTYPE (cyclone curl) curl)
 (CURLOPT_SSLVERSION (cyclone curl) curl)
 (CURLOPT_SSL_CIPHER_LIST (cyclone curl) curl)
 (CURLOPT_SSL_CTX_DATA (cyclone curl) curl)
 (CURLOPT_SSL_CTX_FUNCTION (cyclone curl) curl)
 (CURLOPT_SSL_ENABLE_ALPN (cyclone curl) curl)
 (CURLOPT_SSL_ENABLE_NPN (cyclone curl) curl)
 (CURLOPT_SSL_FALSESTART (cyclone curl) curl)
 (CURLOPT_SSL_OPTIONS (cyclone curl) curl)
 (CURLOPT_SSL_SESSIONID_CACHE (cyclone curl) curl)
 (CURLOPT_SSL_VERIFYHOST (cyclone curl) curl)
 (CURLOPT_SSL_VERIFYPEER (cyclone curl) curl)
 (CURLOPT_SSL_VERIFYSTATUS (cyclone curl) curl)
 (CURLOPT_STDERR (cyclone curl) curl)
 (CURLOPT_STREAM_DEPENDS (cyclone curl) curl)
 (CURLOPT_STREAM_DEPENDS_E (cyclone curl) curl)
 (CURLOPT_STREAM_WEIGHT (cyclone curl) curl)
 (CURLOPT_TCP_KEEPALIVE (cyclone curl) curl)
 (CURLOPT_TCP_KEEPIDLE (cyclone curl) curl)
 (CURLOPT_TCP_KEEPINTVL (cyclone curl) curl)
 (CURLOPT_TCP_NODELAY (cyclone curl) curl)
 (CURLOPT_TELNETOPTIONS (cyclone curl) curl)
 (CURLOPT_TFTP_BLKSIZE (cyclone curl) curl)
 (CURLOPT_TIMECONDITION (cyclone curl) curl)
 (CURLOPT_TIMEOUT (cyclone curl) curl)
 (CURLOPT_TIMEOUT_MS (cyclone curl) curl)
 (CURLOPT_TIMEVALUE (cyclone curl) curl)
 (CURLOPT_TLSAUTH_PASSWORD (cyclone curl) curl)
 (CURLOPT_TLSAUTH_TYPE (cyclone curl) curl)
 (CURLOPT_TLSAUTH_USERNAME (cyclone curl) curl)
 (CURLOPT_TRANSFERTEXT (cyclone curl) curl)
 (CURLOPT_TRANSFER_ENCODING (cyclone curl) curl)
 (CURLOPT_UNIX_SOCKET_PATH (cyclone curl) curl)
 (CURLOPT_UNRESTRICTED_AUTH (cyclone curl) curl)
 (CURLOPT_UPLOAD (cyclone curl) curl)
 (CURLOPT_URL (cyclone curl) curl)
 (CURLOPT_USERAGENT (cyclone curl) curl)
 (CURLOPT_USERNAME (cyclone curl) curl)
 (CURLOPT_USERPWD (cyclone curl) curl)
 (CURLOPT_USE_SSL (cyclone curl) curl)
 (CURLOPT_VERBOSE (cyclone curl) curl)
 (CURLOPT_WILDCARDMATCH (cyclone curl) curl)
 (CURLOPT_WRITEDATA (cyclone curl) curl)
 (CURLOPT_WRITEFUNCTION (cyclone curl) curl)
 (CURLOPT_XFERINFODATA (cyclone curl) curl)
 (CURLOPT_XFERINFOFUNCTION (cyclone curl) curl)
 (CURLOPT_XOAUTH2_BEARER (cyclone curl) curl)
 (Char-Set (cyclone char-set) char-set)
 (DEBUG (cyclone syslog) syslog)
 (EMERG (cyclone syslog) syslog)
 (ERR (cyclone syslog) syslog)
 (INFO (cyclone syslog) syslog)
 (Integer-Set (cyclone iset) iset)
 (LOG_PID (cyclone syslog) syslog)
 (LOG_USER (cyclone syslog) syslog)
 (NOTICE (cyclone syslog) syslog)
 (WARNING (cyclone syslog) syslog)
 (and-> (cyclone clojurian) clojurian)
 (array-list-delete!
   (cyclone array-list)
   array-list)
 (array-list-empty?
   (cyclone array-list)
   array-list)
 (array-list-insert!
   (cyclone array-list)
   array-list)
 (array-list-length
   (cyclone array-list)
   array-list)
 (array-list-ref (cyclone array-list) array-list)
 (array-list-set! (cyclone array-list) array-list)
 (array-list? (cyclone array-list) array-list)
 (as-> (cyclone clojurian) clojurian)
 (assq-ref (cyclone mime) mime)
 (base-generator->results
   (cyclone packrat)
   packrat)
 (base64-decode (cyclone base64) base64)
 (base64-decode-bytevector
   (cyclone base64)
   base64)
 (base64-decode-string (cyclone base64) base64)
 (base64-encode (cyclone base64) base64)
 (base64-encode-bytevector
   (cyclone base64)
   base64)
 (base64-encode-header (cyclone base64) base64)
 (base64-encode-string (cyclone base64) base64)
 (build-parse-tree (cyclone web temple) temple)
 (bytevector->hex-string
   (cyclone bytevector)
   bytevector)
 (bytevector->integer
   (cyclone bytevector)
   bytevector)
 (bytevector-ber-ref
   (cyclone bytevector)
   bytevector)
 (bytevector-ber-set!
   (cyclone bytevector)
   bytevector)
 (bytevector-ieee-double-native-ref
   (cyclone bytevector)
   bytevector)
 (bytevector-ieee-double-native-set!
   (cyclone bytevector)
   bytevector)
 (bytevector-ieee-double-ref
   (cyclone bytevector)
   bytevector)
 (bytevector-ieee-double-set!
   (cyclone bytevector)
   bytevector)
 (bytevector-ieee-single-native-ref
   (cyclone bytevector)
   bytevector)
 (bytevector-ieee-single-native-set!
   (cyclone bytevector)
   bytevector)
 (bytevector-ieee-single-set!
   (cyclone bytevector)
   bytevector)
 (bytevector-pad-left
   (cyclone bytevector)
   bytevector)
 (bytevector-u16-ref-be
   (cyclone bytevector)
   bytevector)
 (bytevector-u16-ref-le
   (cyclone bytevector)
   bytevector)
 (bytevector-u32-ref-be
   (cyclone bytevector)
   bytevector)
 (bytevector-u32-ref-le
   (cyclone bytevector)
   bytevector)
 (call-with-input-string (cyclone string) string)
 (call-with-output-string (cyclone string) string)
 (chain (srfi 197) srfi-197)
 (chain-and (srfi 197) srfi-197)
 (chain-lambda (srfi 197) srfi-197)
 (chain-when (srfi 197) srfi-197)
 (char-set (cyclone char-set) char-set)
 (char-set->list (cyclone char-set) char-set)
 (char-set->string (cyclone char-set) char-set)
 (char-set-adjoin (cyclone char-set) char-set)
 (char-set-adjoin! (cyclone char-set) char-set)
 (char-set-complement (cyclone char-set) char-set)
 (char-set-contains? (cyclone char-set) char-set)
 (char-set-copy (cyclone char-set) char-set)
 (char-set-difference (cyclone char-set) char-set)
 (char-set-difference!
   (cyclone char-set)
   char-set)
 (char-set-fold (cyclone char-set) char-set)
 (char-set-for-each (cyclone char-set) char-set)
 (char-set-intersection
   (cyclone char-set)
   char-set)
 (char-set-intersection!
   (cyclone char-set)
   char-set)
 (char-set-size (cyclone char-set) char-set)
 (char-set-union (cyclone char-set) char-set)
 (char-set-union! (cyclone char-set) char-set)
 (char-set:ascii (cyclone char-set) char-set)
 (char-set:empty (cyclone char-set) char-set)
 (char-set:full (cyclone char-set) char-set)
 (char-set? (cyclone char-set) char-set)
 (close-pipe-port (cyclone io popen) popen)
 (closelog (cyclone syslog) syslog)
 (csv-read (cyclone csv) csv)
 (csv-read-all (cyclone csv) csv)
 (csv-write (cyclone csv) csv)
 (csv-write-all (cyclone csv) csv)
 (curl-easy-cleanup (cyclone curl) curl)
 (curl-easy-init (cyclone curl) curl)
 (curl-easy-perform (cyclone curl) curl)
 (curl-easy-setopt (cyclone curl) curl)
 (curl-global-init (cyclone curl) curl)
 (curl-version (cyclone curl) curl)
 (cut (srfi 26) srfi-26)
 (cute (srfi 26) srfi-26)
 (doto (cyclone clojurian) clojurian)
 (elapsed (cyclone benchmark) benchmark)
 (end-of-iset? (cyclone iset) iset)
 (get-parse-tree (cyclone web temple) temple)
 (hex-string->bytevector
   (cyclone bytevector)
   bytevector)
 (hex-string->integer
   (cyclone bytevector)
   bytevector)
 (html-escape (cyclone sxml) sxml)
 (html-tag->string (cyclone sxml) sxml)
 (if-let (cyclone clojurian) clojurian)
 (if-let* (cyclone clojurian) clojurian)
 (immutable-char-set (cyclone char-set) char-set)
 (integer->bytevector
   (cyclone bytevector)
   bytevector)
 (integer->hex-string
   (cyclone bytevector)
   bytevector)
 (irregex (cyclone irregex) irregex)
 (irregex-dfa (cyclone irregex) irregex)
 (irregex-dfa/search (cyclone irregex) irregex)
 (irregex-extract (cyclone irregex) irregex)
 (irregex-flags (cyclone irregex) irregex)
 (irregex-fold (cyclone irregex) irregex)
 (irregex-lengths (cyclone irregex) irregex)
 (irregex-match (cyclone irregex) irregex)
 (irregex-match (cyclone irregex) irregex)
 (irregex-match-data? (cyclone irregex) irregex)
 (irregex-match-end-chunk
   (cyclone irregex)
   irregex)
 (irregex-match-end-index
   (cyclone irregex)
   irregex)
 (irregex-match-names (cyclone irregex) irregex)
 (irregex-match-num-submatches
   (cyclone irregex)
   irregex)
 (irregex-match-start-chunk
   (cyclone irregex)
   irregex)
 (irregex-match-start-index
   (cyclone irregex)
   irregex)
 (irregex-match-subchunk
   (cyclone irregex)
   irregex)
 (irregex-match-substring
   (cyclone irregex)
   irregex)
 (irregex-match-valid-index?
   (cyclone irregex)
   irregex)
 (irregex-match/chunked (cyclone irregex) irregex)
 (irregex-names (cyclone irregex) irregex)
 (irregex-new-matches (cyclone irregex) irregex)
 (irregex-nfa (cyclone irregex) irregex)
 (irregex-num-submatches
   (cyclone irregex)
   irregex)
 (irregex-replace (cyclone irregex) irregex)
 (irregex-replace/all (cyclone irregex) irregex)
 (irregex-reset-matches!
   (cyclone irregex)
   irregex)
 (irregex-search (cyclone irregex) irregex)
 (irregex-search (cyclone irregex) irregex)
 (irregex-search/chunked
   (cyclone irregex)
   irregex)
 (irregex-search/matches
   (cyclone irregex)
   irregex)
 (irregex-split (cyclone irregex) irregex)
 (irregex? (cyclone irregex) irregex)
 (iset (cyclone iset) iset)
 (iset->list (cyclone iset) iset)
 (iset-adjoin (cyclone iset) iset)
 (iset-adjoin! (cyclone iset) iset)
 (iset-contains? (cyclone iset) iset)
 (iset-copy (cyclone iset) iset)
 (iset-cursor (cyclone iset) iset)
 (iset-cursor-next (cyclone iset) iset)
 (iset-cursor? (cyclone iset) iset)
 (iset-delete (cyclone iset) iset)
 (iset-delete! (cyclone iset) iset)
 (iset-difference (cyclone iset) iset)
 (iset-difference! (cyclone iset) iset)
 (iset-empty? (cyclone iset) iset)
 (iset-fold (cyclone iset) iset)
 (iset-fold-node (cyclone iset) iset)
 (iset-for-each (cyclone iset) iset)
 (iset-for-each-node (cyclone iset) iset)
 (iset-intersection (cyclone iset) iset)
 (iset-intersection! (cyclone iset) iset)
 (iset-map (cyclone iset) iset)
 (iset-ref (cyclone iset) iset)
 (iset-size (cyclone iset) iset)
 (iset-union (cyclone iset) iset)
 (iset-union! (cyclone iset) iset)
 (iset<= (cyclone iset) iset)
 (iset= (cyclone iset) iset)
 (iset>= (cyclone iset) iset)
 (iset? (cyclone iset) iset)
 (json->scm (cyclone json) json)
 (json-read (cyclone json) json)
 (json-write (cyclone json) json)
 (list->char-set (cyclone char-set) char-set)
 (list->iset (cyclone iset) iset)
 (list->iset! (cyclone iset) iset)
 (make-array-list (cyclone array-list) array-list)
 (make-csv-reader (cyclone csv) csv)
 (make-csv-writer (cyclone csv) csv)
 (make-error-expected (cyclone packrat) packrat)
 (make-error-message (cyclone packrat) packrat)
 (make-expected-result (cyclone packrat) packrat)
 (make-irregex-chunker (cyclone irregex) irregex)
 (make-iset (cyclone iset) iset)
 (make-message-result (cyclone packrat) packrat)
 (make-parse-position (cyclone packrat) packrat)
 (make-path (cyclone pathname) pathname)
 (make-result (cyclone packrat) packrat)
 (make-string-searcher (cyclone string) string)
 (make-uri (cyclone uri) uri)
 (maybe-string->sre (cyclone irregex) irregex)
 (md5 (cyclone crypto md5) md5)
 (merge-parse-errors (cyclone packrat) packrat)
 (merge-result-errors (cyclone packrat) packrat)
 (mime-decode-header (cyclone mime) mime)
 (mime-header-fold (cyclone mime) mime)
 (mime-headers->list (cyclone mime) mime)
 (mime-message->sxml (cyclone mime) mime)
 (mime-message-fold (cyclone mime) mime)
 (mime-parse-content-type (cyclone mime) mime)
 (mime-write-headers (cyclone mime) mime)
 (nest (srfi 197) srfi-197)
 (nest-reverse (srfi 197) srfi-197)
 (open-input-pipe (cyclone io popen) popen)
 (open-log (cyclone syslog) syslog)
 (openlog (cyclone syslog) syslog)
 (packrat-check (cyclone packrat) packrat)
 (packrat-check-base (cyclone packrat) packrat)
 (packrat-or (cyclone packrat) packrat)
 (packrat-parser (cyclone packrat) packrat)
 (packrat-unless (cyclone packrat) packrat)
 (parse-error-empty? (cyclone packrat) packrat)
 (parse-error-expected (cyclone packrat) packrat)
 (parse-error-messages (cyclone packrat) packrat)
 (parse-error-position (cyclone packrat) packrat)
 (parse-error? (cyclone packrat) packrat)
 (parse-position->string
   (cyclone packrat)
   packrat)
 (parse-position-column (cyclone packrat) packrat)
 (parse-position-file (cyclone packrat) packrat)
 (parse-position-line (cyclone packrat) packrat)
 (parse-position>? (cyclone packrat) packrat)
 (parse-position? (cyclone packrat) packrat)
 (parse-result-error (cyclone packrat) packrat)
 (parse-result-next (cyclone packrat) packrat)
 (parse-result-semantic-value
   (cyclone packrat)
   packrat)
 (parse-result-successful?
   (cyclone packrat)
   packrat)
 (parse-result? (cyclone packrat) packrat)
 (parse-results-base (cyclone packrat) packrat)
 (parse-results-next (cyclone packrat) packrat)
 (parse-results-position
   (cyclone packrat)
   packrat)
 (parse-results-token-kind
   (cyclone packrat)
   packrat)
 (parse-results-token-value
   (cyclone packrat)
   packrat)
 (parse-results? (cyclone packrat) packrat)
 (path-absolute? (cyclone pathname) pathname)
 (path-directory (cyclone pathname) pathname)
 (path-extension (cyclone pathname) pathname)
 (path-normalize (cyclone pathname) pathname)
 (path-relative-to (cyclone pathname) pathname)
 (path-relative? (cyclone pathname) pathname)
 (path-replace-extension
   (cyclone pathname)
   pathname)
 (path-resolve (cyclone pathname) pathname)
 (path-strip-directory
   (cyclone pathname)
   pathname)
 (path-strip-extension
   (cyclone pathname)
   pathname)
 (path-strip-leading-parents
   (cyclone pathname)
   pathname)
 (pclose (cyclone io popen) popen)
 (perf-counter (cyclone benchmark) benchmark)
 (popen (cyclone io popen) popen)
 (prepend-base (cyclone packrat) packrat)
 (prepend-semantic-value
   (cyclone packrat)
   packrat)
 (py-call (cyclone python) python)
 (py-def (cyclone python) python)
 (py-def-attribute (cyclone python) python)
 (py-def-method (cyclone python) python)
 (py-import (cyclone python) python)
 (py-run-file (cyclone python) python)
 (py-run-simple-string (cyclone python) python)
 (py-start (cyclone python) python)
 (py-stop (cyclone python) python)
 (py-value (cyclone python) python)
 (quoted-printable-decode
   (cyclone quoted-printable)
   quoted-printable)
 (quoted-printable-decode-bytevector
   (cyclone quoted-printable)
   quoted-printable)
 (quoted-printable-decode-string
   (cyclone quoted-printable)
   quoted-printable)
 (quoted-printable-encode
   (cyclone quoted-printable)
   quoted-printable)
 (quoted-printable-encode-bytevector
   (cyclone quoted-printable)
   quoted-printable)
 (quoted-printable-encode-header
   (cyclone quoted-printable)
   quoted-printable)
 (quoted-printable-encode-string
   (cyclone quoted-printable)
   quoted-printable)
 (read-all-from-pipe (cyclone io popen) popen)
 (read-lines-from-pipe (cyclone io popen) popen)
 (render (cyclone web temple) temple)
 (results->result (cyclone packrat) packrat)
 (reverse-list->string (srfi 152) srfi-152)
 (scm->json (cyclone json) json)
 (send-log (cyclone syslog) syslog)
 (setlogmask (cyclone syslog) syslog)
 (sha-224 (cyclone crypto sha2) sha2)
 (sha-256 (cyclone crypto sha2) sha2)
 (sre->irregex (cyclone irregex) irregex)
 (string->char-set (cyclone char-set) char-set)
 (string->irregex (cyclone irregex) irregex)
 (string->path-uri (cyclone uri) uri)
 (string->sre (cyclone irregex) irregex)
 (string->uri (cyclone uri) uri)
 (string-any (srfi 152) srfi-152)
 (string-any (cyclone string) string)
 (string-break (srfi 152) srfi-152)
 (string-ci<=? (srfi 152) srfi-152)
 (string-ci<? (srfi 152) srfi-152)
 (string-ci=? (srfi 152) srfi-152)
 (string-ci>=? (srfi 152) srfi-152)
 (string-ci>? (srfi 152) srfi-152)
 (string-concatenate (srfi 152) srfi-152)
 (string-concatenate-reverse (srfi 152) srfi-152)
 (string-contains (srfi 152) srfi-152)
 (string-contains (cyclone string) string)
 (string-contains-right (srfi 152) srfi-152)
 (string-count (srfi 152) srfi-152)
 (string-count (cyclone string) string)
 (string-cursor->index (cyclone string) string)
 (string-cursor-back (cyclone string) string)
 (string-cursor-end (cyclone string) string)
 (string-cursor-forward (cyclone string) string)
 (string-cursor-next (cyclone string) string)
 (string-cursor-prev (cyclone string) string)
 (string-cursor-ref (cyclone string) string)
 (string-cursor-start (cyclone string) string)
 (string-cursor<=? (cyclone string) string)
 (string-cursor<? (cyclone string) string)
 (string-cursor=? (cyclone string) string)
 (string-cursor>=? (cyclone string) string)
 (string-cursor>? (cyclone string) string)
 (string-cursor? (cyclone string) string)
 (string-downcase-ascii (cyclone string) string)
 (string-drop (srfi 152) srfi-152)
 (string-drop-right (srfi 152) srfi-152)
 (string-drop-while (srfi 152) srfi-152)
 (string-drop-while-right (srfi 152) srfi-152)
 (string-every (srfi 152) srfi-152)
 (string-every (cyclone string) string)
 (string-filter (srfi 152) srfi-152)
 (string-find (cyclone string) string)
 (string-find-right (cyclone string) string)
 (string-find? (cyclone string) string)
 (string-fold (cyclone string) string)
 (string-fold (srfi 152) srfi-152)
 (string-fold-right (srfi 152) srfi-152)
 (string-fold-right (cyclone string) string)
 (string-for-each (cyclone string) string)
 (string-index (srfi 152) srfi-152)
 (string-index->cursor (cyclone string) string)
 (string-index-right (srfi 152) srfi-152)
 (string-join (srfi 152) srfi-152)
 (string-join (cyclone string) string)
 (string-map (cyclone string) string)
 (string-mismatch (cyclone string) string)
 (string-mismatch-right (cyclone string) string)
 (string-null? (srfi 152) srfi-152)
 (string-null? (cyclone string) string)
 (string-pad (srfi 152) srfi-152)
 (string-pad-right (srfi 152) srfi-152)
 (string-prefix-length (srfi 152) srfi-152)
 (string-prefix? (srfi 152) srfi-152)
 (string-prefix? (cyclone string) string)
 (string-remove (srfi 152) srfi-152)
 (string-replace (srfi 152) srfi-152)
 (string-replicate (srfi 152) srfi-152)
 (string-segment (srfi 152) srfi-152)
 (string-skip (srfi 152) srfi-152)
 (string-skip (cyclone string) string)
 (string-skip-right (srfi 152) srfi-152)
 (string-skip-right (cyclone string) string)
 (string-span (srfi 152) srfi-152)
 (string-split (srfi 152) srfi-152)
 (string-split (cyclone string) string)
 (string-suffix-length (srfi 152) srfi-152)
 (string-suffix? (srfi 152) srfi-152)
 (string-suffix? (cyclone string) string)
 (string-tabulate (srfi 152) srfi-152)
 (string-take (srfi 152) srfi-152)
 (string-take-right (srfi 152) srfi-152)
 (string-take-while (srfi 152) srfi-152)
 (string-take-while-right (srfi 152) srfi-152)
 (string-trim (srfi 152) srfi-152)
 (string-trim (cyclone string) string)
 (string-trim-both (srfi 152) srfi-152)
 (string-trim-left (cyclone string) string)
 (string-trim-right (srfi 152) srfi-152)
 (string-trim-right (cyclone string) string)
 (string-unfold (srfi 152) srfi-152)
 (string-unfold-right (srfi 152) srfi-152)
 (string-upcase-ascii (cyclone string) string)
 (string<=? (srfi 152) srfi-152)
 (string<? (srfi 152) srfi-152)
 (string=? (srfi 152) srfi-152)
 (string>=? (srfi 152) srfi-152)
 (string>? (srfi 152) srfi-152)
 (substring-cursor (cyclone string) string)
 (sxml->xml (cyclone sxml) sxml)
 (sxml-display-as-html (cyclone sxml) sxml)
 (sxml-display-as-text (cyclone sxml) sxml)
 (sxml-strip (cyclone sxml) sxml)
 (syslog (cyclone syslog) syslog)
 (test-me
   (cyclone dummy-test-package)
   dummy-test-package)
 (top-parse-position (cyclone packrat) packrat)
 (ucs-range->char-set (cyclone char-set) char-set)
 (update-parse-position (cyclone packrat) packrat)
 (uri->string (cyclone uri) uri)
 (uri-alist->query (cyclone uri) uri)
 (uri-decode (cyclone uri) uri)
 (uri-encode (cyclone uri) uri)
 (uri-fragment (cyclone uri) uri)
 (uri-has-scheme? (cyclone uri) uri)
 (uri-host (cyclone uri) uri)
 (uri-path (cyclone uri) uri)
 (uri-port (cyclone uri) uri)
 (uri-query (cyclone uri) uri)
 (uri-query->alist (cyclone uri) uri)
 (uri-resolve (cyclone uri) uri)
 (uri-scheme (cyclone uri) uri)
 (uri-user (cyclone uri) uri)
 (uri-with-fragment (cyclone uri) uri)
 (uri-with-host (cyclone uri) uri)
 (uri-with-path (cyclone uri) uri)
 (uri-with-query (cyclone uri) uri)
 (uri-with-scheme (cyclone uri) uri)
 (uri-with-user (cyclone uri) uri)
 (uri? (cyclone uri) uri)
 (with-input-from-pipe (cyclone io popen) popen)
 (with-python (cyclone python) python))
