name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:    
      matrix:
        arch: [64]

    steps:
    # Install dependencies
    - name: Install libck
      run: sudo apt-get install libck-dev    
    - name: Install Cyclone
      run: |
        wget https://github.com/cyclone-scheme/binary-releases/raw/master/ubuntu-18.04-lts/cyclone-scheme_0.30.0_amd64.deb 
        sudo apt install ./cyclone-scheme_0.30.0_amd64.deb
      
    # Setup winds
    - uses: actions/checkout@v2
    - name: Build Winds
      run: make
    - name: Install Winds
      run: sudo make install
      
    # Run our tests
    - name: Run tests
      run: |
        make test
        
    # -----------------------------------------------------------------
    # Run system tasks (the order is important!)

    # Pre-requisite
    - name: Clone wiki directory
      run: |
        git clone https://github.com/cyclone-scheme/winds.wiki.git ~/wiki

    # Update wiki index, packages wikis and library/definition indexes.
    # One command does all to avoid multiple iterations over all packages,
    # which could become too slow as the packages list grows.
    - name: Update wiki and library index
      run: |
        make sys-tasks
        make clean

    # Wiki index (already updated by 'make sys-tasks')
    # Got from https://github.com/marketplace/actions/wiki-sync        
    - name: Push wiki changes
      uses: joeizzard/action-wiki-sync@master
      with:
          username: ${{ github.repository_owner }}
          access_token: ${{ secrets.GITHUB_TOKEN }}
          wiki_folder: wiki
          commit_username: ${{ github.repository_owner }}
          commit_email: ${{ secrets.AUTOMATION_EMAIL }}
          commit_message: 'Updated wiki'

    - name: Clean wiki directory
      run: |
        rm -Rf wiki

    # Library index
    - name: Commit library index
      run: |
        git config --local user.email ${{ secrets.AUTOMATION_EMAIL }}
        git config --local user.name ${{ github.repository_owner }}
        git add ./indexes/library-index.scm
        [[ -z $(git status -s) ]] || git commit -m "Updated library-index.scm on push"

    # Definition index
    - name: Commit definition index
      run: |
        git config --local user.email ${{ secrets.AUTOMATION_EMAIL }}
        git config --local user.name ${{ github.repository_owner }}
        git add ./indexes/definition-index.scm
        [[ -z $(git status -s) ]] || git commit -m "Updated definition-index.scm on push"
    
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true


    
